# Generated by Django 5.2.4 on 2025-08-11 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='printer',
            name='farm_printe_handler_974661_idx',
        ),
        migrations.AddField(
            model_name='printer',
            name='info_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='info_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_info', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='handler_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printer',
            name='handler_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printer_handler', to='contenttypes.contenttype'),
        ),
    ]
