# Generated by Django 5.2.4 on 2025-08-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrusaLinkConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'PrusaLink Connection',
                'verbose_name_plural': 'PrusaLink Connections',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
