# Generated by Django 5.2.4 on 2025-08-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prslnk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrusaLinkPrinterInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.CharField(default='Prusa Research', max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
