# Generated by Django 5.2.4 on 2025-08-12 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prslnk', '0002_prusalinkprinterinfomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prusalinkprinterinfomodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Printer Info', 'verbose_name_plural': 'Printer Info Objects'},
        ),
    ]
