# Generated by Django 5.2.4 on 2025-07-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoonrakerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("api_key", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Moonraker Connection",
                "verbose_name_plural": "Moonraker Connections",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
